# App
spring.application.name=cloudbridge
server.port=8080

# PostgreSQL
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver.class-name=

# JAP / Hibernate
spring.jpa.database-platform=
spring.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload limit
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

# AWS S3
aws.access-key=${}
aws.secret-key=${}
aws.region=
aws.bucket-name=${}

# Azure


# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${}
spring.mail.password=${}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Temp storage
cloudbridge.temp-dir=
cloudbridge.upload-dir=

# Link expiry
cloudbridge.default-expiry-hours=24